module Problem002

  def self.description 
%*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*
  end

  def self.answer
    fibs = [1, 2]
    sum  = 2 

    until fibs.last >= 4000000
      next_fib = fibs[-1] + fibs[-2]
      sum = sum + next_fib if next_fib.even?
      fibs.push next_fib
    end

    sum
  end
end